# Generated by Django 4.2.2 on 2023-06-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='images')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Ceramika'), (0, 'Malarstwo')], default=0)),
            ],
        ),
    ]
