# Generated by Django 4.2.2 on 2023-06-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szartapp', '0003_product_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ceramika'), (0, 'Malarstwo')], default=0),
        ),
    ]
