# Generated by Django 4.2.2 on 2023-06-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szartapp', '0007_cart_order_alter_like_like_orderitem_order_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='image',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='image',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.PositiveSmallIntegerField(choices=[(0, 'niepolubione'), (1, 'polubione')], default=0),
        ),
    ]
