# Generated by Django 4.2.2 on 2023-06-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szartapp', '0008_rename_image_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.PositiveSmallIntegerField(choices=[(1, 'polubione'), (0, 'niepolubione')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Malarstwo'), (1, 'Ceramika')], default=0),
        ),
    ]
