# Generated by Django 4.2.2 on 2023-07-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szartapp', '0009_cart_total_price_alter_like_like_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nadawca', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('temat', models.CharField(max_length=200)),
                ('tresc', models.TextField()),
            ],
        ),
    ]
