# Generated by Django 4.2.2 on 2023-07-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szartapp', '0011_product_short_desc_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Kup'), (1, 'Zapytaj o podobne')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Malarstwo'), (1, 'Ceramika')], default=0),
        ),
    ]
